### PR TITLE
normandy-devtools 1.0.0

### PR DESCRIPTION
**Pull request by escapewindow**
This should fix the current bustage, but ideally we can remove the version from the filename to make things more deterministic.

### CODE REVIEW

**Comment by rehandalal** [comment]
let's get rid of the version number for now and I'll update normandy devtools accordingly.

**Comment by escapewindow** [comment]
Done. We have the option of naming it anything else (.xpi?) but this should work once the build creates this path.

**Comment by rehandalal** [comment]
> We have the option of naming it anything else (.xpi?) but this should work once the build creates this path.

So it actually turns out renaming the file is less straightforward than anticipated since [web-ext](https://github.com/mozilla/web-ext) does not support an output file name for its `build` command. I'm trying to figure out the best way to do this but ostensibly we could change the extension to `.xpi`.

**Comment by rehandalal** [comment]
I just went to go file an issue and noticed you beat me to it. Thanks!

**Comment by escapewindow** [comment]
If we want to get this working sooner, the fix is to rename to 1.0.0.

**Comment by rehandalal** [comment]
i have a PR open to rename this on that repo with an additional step

**Pull request merged**
