### PR TITLE
Run taskgraph generation with Python 3

### PR DESCRIPTION
**Pull request by ahal**
We're updating consumers of taskgraph to Python 3 so we can drop Python 2 support.

This fixes RELENG-611

### CODE REVIEW

**Review by escapewindow — APPROVED** [review]
Invited you to the org. Once you join, we can close/reopen and the tasks should run.

This looks good, thank you!

xpi-manifest runs all of our release graphs for the addons-pipeline; we should be good with this PR. We also have https://github.com/mozilla-extensions/xpi-template which contains our CI automation; each source repo in the [organization](https://github.com/mozilla-extensions/) then copies that .tc.yml in, pulls xpi-template/master for its taskcluster/ dir, and runs CI on push.

This presents a bit of an issue: how to upgrade the xpi-template repo without breaking all CI for all addons repos. One way is to land a six-compatibility PR, update all the source .tc.yml's over time, remove the compatibility layer when we're done, and we're good. Another way may be to create a `main` branch on xpi-template, land the py3 changes, move the source repos to py3 and the main branch over time, and delete the `master` branch when we're done.

**Comment by ahal** [comment]
Sounds like some more items for the Py3 backlog :)

I prefer a 2 and 3 compatibility layer over making a separate branch. But I'm not sure how this would work as we'd need to use either `pip` or `pip3` in `.taskcluster.yml` depending. Would consumers be able to override this?

On the other hand, if the template repo rarely ever changes, maybe the separate branch approach would be a bit faster and easier anyway?

**Comment by escapewindow** [comment]
Invited you to the org. Once you join, we can close/reopen and the tasks should run.

One comment --

**Comment by escapewindow** [comment]
> Error: HTTP status client error (404 Not Found) for url (https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/M5TIcKA6Qgad-vZ04jTd8g/artifacts/public/docker-contexts/node-15.tar.gz)

This is the PR decision task, looks like?
I don't know what we're doing with the docker-contexts, but looks like taskgraph now expects those to be created, and our PR decision task doesn't, for whatever reason(s).

**Comment by escapewindow** [comment]
> > Error: HTTP status client error (404 Not Found) for url (https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/M5TIcKA6Qgad-vZ04jTd8g/artifacts/public/docker-contexts/node-15.tar.gz)
> 
> This is the PR decision task, looks like?
> I don't know what we're doing with the docker-contexts, but looks like taskgraph now expects those to be created, and our PR decision task doesn't, for whatever reason(s).

I'm not seeing anything obvious. Maybe something something running off an untrusted fork?

**Comment by escapewindow** [comment]
Hm,

> [task 2021-07-22T20:08:19.516Z] 2021-07-22 20:08:19,515 - INFO - Writing docker-contexts/node-latest.tar.gz for docker image node-latest
> [task 2021-07-22T20:08:19.531Z] 2021-07-22 20:08:19,531 - INFO - Writing docker-contexts/node-14.tar.gz for docker image node-14
> [task 2021-07-22T20:08:19.546Z] 2021-07-22 20:08:19,546 - INFO - Writing docker-contexts/node-15.tar.gz for docker image node-15

Now I'm guessing we're writing these artifacts to the wrong directory?

**Review by escapewindow — CHANGES_REQUESTED** [review]
Aha, we probably want [this block](https://hg.mozilla.org/ci/taskgraph/file/tip/.taskcluster.yml#l192) in .tc.yml

**Comment by ahal** [comment]
Sorry, I probably should have marked this as a draft PR :). Yeah I've been needing to add that block to a lot of these and forgot to do it here.

**Review by escapewindow — APPROVED** [review]
Thank you!

**Pull request merged**
