### PR TITLE
add firefox ci quitter extension to xpi release process

### PR DESCRIPTION
**Pull request by jmaher**

### CODE REVIEW

**Comment by escapewindow** [comment]
We're missing the manifest.

**Comment by escapewindow** [comment]
@jmaher Looks like we don't have a package.json ?
Have you gotten the CI green in your repo yet?

> [task 2022-08-29T23:05:31.398Z] Exception: Can't find package.json in /builds/worker/checkouts/vcs!

**Comment by jmaher** [comment]
I spent a bit of time yesterday unsuccessful, planning to get it going smooth in my repo and get these tasks green- will ping you when it is ready for review

**Comment by jmaher** [comment]
I have updated my repo, the tests pass in my repo:
https://github.com/mozilla-extensions/quitter

and they pass here.

@escapewindow if you have time, please review and merge when ready

**Review by escapewindow — APPROVED** [review]
Looks good! Please set [branch protections](https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md#branch-protection) on the quitter repo.

**Comment by jmaher** [comment]
the link to branch protections is broken:
https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuring-protected-branches

and the link to secops is broken also:
https://mana.mozilla.org/wiki/pages/viewpage.action?spaceKey=SVCOPS&title=Firefox+Operations+Security

I have emailed secops+github already.

**Comment by escapewindow** [comment]
Should probably be https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches for the github side.

**Pull request merged**
