### PR TITLE
Remove integrations for Rally Core Add-on and Rally Search Engine Usage Study

### PR DESCRIPTION
**Pull request by aaga**
Removes all references to `rally-core-addon` and `search-engine-usage-study`, because the Mozilla Rally project has been decommissioned.

**Note** that there are 3 test files that seem to rely on the `rally-core-addon`:
- https://github.com/mozilla-extensions/xpi-manifest/blob/main/taskcluster/test/params/privileged-build.yml#L29
- https://github.com/mozilla-extensions/xpi-manifest/blob/main/taskcluster/test/params/privileged-promote.yml#L67
- https://github.com/mozilla-extensions/xpi-manifest/blob/main/taskcluster/test/params/privileged-ship.yml#L70

I've left them alone for now, and CI checks seem to still pass. Feel free to remove them in another commit if needed.

### CODE REVIEW

**Comment by wagnerand** [comment]
> @wagnerand, the comment around ID_ALLOWLIST says to double check with you before any change, can you confirm this one?

Hm, I am not sure actually if we shouldn't keep that one in for a bit longer (or forever). This is protect takeover of an add-on that was signed outside of AMO by using the same ID on AMO.
@aaga can you confirm that all rally extensions (that have an ID ending with `@rally.mozilla.org`) have also been submitted to AMO are owned by the Rally team account?

**Comment by aaga** [comment]
I see this is already merged (thanks @gabrielBusta !) but @wagnerand I'm not sure I fully understand your question.

I can confirm that all Rally extensions have `addons-team@mozilla.com` listed as an owner, in addition to me and rhelmer. What would be an example of a Rally extension that hasn't been submitted to AMO?

**Comment by aaga** [comment]
Oh never mind, just saw that this was reverted.

**Comment by wagnerand** [comment]
> What would be an example of a Rally extension that hasn't been submitted to AMO?

My question was if such an extension exists.

**Comment by aaga** [comment]
Any and all Rally extensions have been only submitted through AMO. There are some test versions/updates that were never submitted to AMO (e.g. the Search Engine Study relaunch), but these were not submitted to anywhere else either.

Also, there are two Rally extensions with id `@mozilla.org`, if that is relevant.

**Comment by gabrielBusta** [comment]
I have reverted the changes. I initially misunderstood @wagnerand's comment. Then, I re-read it after the merge and realized it should be addressed before merging these changes. I wish you could re-open a PR on Github. Alas, you cannot. You will need to create a new pull request, copying all the details over and providing a link this original PR.

**Comment by gabrielBusta** [comment]
I reverted the changes. I initially misunderstood @wagnerand's comment. Then, I re-read it after the merge and realized it should be addressed before merging these changes. I wish you could re-open a PR on Github. Alas, you cannot. You will need to create a new pull request, copying all the details over and providing a link this original PR.

**Comment by aaga** [comment]
https://github.com/mozilla-extensions/xpi-manifest/pull/203

**Pull request merged**
