### PR TITLE
Add QuickSuggest Adm

### PR DESCRIPTION
**Pull request by daleharvey**

### CODE REVIEW

**Comment by daleharvey** [comment]
Restarting as this was failing with a name mistmatch, updated the source repo so the name matches

**Review by escapewindow — CHANGES_REQUESTED** [review]
It looks like the dep-signing task expects a `quick-suggest-extension.xpi`. It gets this name from the [name in package.json](https://github.com/mozilla-extensions/firefox-quick-suggest-adm/blob/master/package.json#L2).

We can land this as-is if you either don't need dep-signing in CI, or if you plan on changing the name to `firefox-quick-suggest-adm` in package.json. What do you think?

**Comment by daleharvey** [comment]
Ah I was thinking dep-signing would fail until this was setup, sorry was a big assumption. Thanks for the pointer, I have updated to match so its `firefox-quick-suggest-adm` now

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
Your dep signing's green now, congratulations!
Thank you!

**Pull request merged**
