### PR TITLE
Add Bergamot Browser Extension xpi

### PR DESCRIPTION
**Pull request by motin**
As per https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md#enabling-releases

### CODE REVIEW

**Comment by motin** [comment]
Seems to be a catch 22 here. The PR checks out the main branch of the repo, but that branch is only for released code, which in turn requires this PR to be merged.

**Review by escapewindow — CHANGES_REQUESTED** [review]
This is broken because `yarn build` doesn't appear to work.
Looking at https://github.com/mozilla-extensions/bergamot-browser-extension/blob/main/extension/package.json , there is no `build`script defined. Please follow the steps in https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md to set up taskcluster CI; when that goes green we should be able to see this PR go green as well.

**Comment by motin** [comment]
> This is broken because `yarn build` doesn't appear to work.
> Looking at https://github.com/mozilla-extensions/bergamot-browser-extension/blob/main/extension/package.json , there is no `build`script defined. Please follow the steps in https://github.com/mozilla-extensions/xpi-manifest/blob/master/docs/adding-a-new-xpi.md to set up taskcluster CI; when that goes green we should be able to see this PR go green as well.

Thanks @escapewindow, the plain `build` script is being added in https://github.com/mozilla-extensions/bergamot-browser-extension/pull/41, but it doesn't exist yet on the main branch. It will only exist in the main branch after the next release, since that is when the main branch gets updated. 

Should I change the branch config in this PR to point to another branch just to check that it works as expected before the next release, or is it better to revisit this PR after the next release of the extension - eg when the extension's main branch has a working `build` script? Both ways are fine for us :)

**Comment by escapewindow** [comment]
That's interesting. The mozilla-extensions automation assumes that we're pointed at the branch where the next release candidate(s) are coming from, because the QA process may find that we want to abandon the current build and add code to fix the next release candidate.

That may mean we want to use the next-release branch. Alternately we can wait until the release is on the main branch, but then continue iterating on the main branch until the xpi is ready to release.

**Comment by escapewindow** [comment]
The build appears broken because the built xpi and the expected xpi path differ:
```
[task 2021-02-24T19:46:37.133Z] Your web extension is ready: dist/firefox/native-ui/translation_mozilla.org.xpi
[task 2021-02-24T19:46:37.170Z] Exception: Missing artifact extension/dist/firefox/native-ui/translation_mozilla.org.xpi
```

In addition, the CI will expect the built xpi name and the `name` in package.json to match.

**Comment by motin** [comment]
> That may mean we want to use the next-release branch. Alternately we can wait until the release is on the main branch, but then continue iterating on the main branch until the xpi is ready to release.

Fyi, we will be using the main branch instead of the next-release branch to iterate until the xpi is ready to release. Will update the manifest to reflect this once the above mentioned PR has been merged to the main branch.

**Review by escapewindow — APPROVED** [review]
Looks good, thank you!

If we're planning on releasing the extension bundled with the browser (per #addons-pipeline), should this extension be a system addon, in [`browser/extensions`](https://hg.mozilla.org/mozilla-central/file/tip/browser/extensions)? That would give us system-addon signing for free, and ship with firefox nightly, beta, release, esr as the code rides the trains.

If so, we may either a) not need this PR, or b) we may want to change the format to `system` to match. If we're planning on releasing this addon as a study shipped through normandy, then `normandy-privileged` makes sense.

I'm approving because the PR looks good, assuming we want to keep it as a `normandy-privileged` addon. I'll hold off merging until we resolve the above question.

**Comment by motin** [comment]
Very apt question indeed. :) The plan is to first launch an add-on experiment via Normandy before deciding about the inclusion of the feature as a bundled extension with the browser.

**Comment by escapewindow** [comment]
It seems worth asking if it'll be problematic if the addon is privileged first, then system later, before releasing. I'll go ahead and merge this PR and we can revisit if we come to a different conclusion.

Thanks!

**Comment by mixedpuppy** [comment]
Some clarifying comments:

a) Including an addon in Firefox means it is not signed at all.
b) If you choose to land in m-c and distribute that way, I would prefer it is a builtin addon as I'd like to transition away from any system addons in-tree.  If it gets to that point I can help with how this is done.  The meaningful difference here is that "builtin" addons are built into the jar which is signed, system addons are not (refer to A).
c) addons in-tree are privileged automatically.

**Pull request merged**
