### PR TITLE
Remove kewisch

### PR DESCRIPTION
**Pull request by wagnerand**
- xpi-template/main
- Remove kewisch

### CODE REVIEW

**Comment by wagnerand** [comment]
Looks like the main branch is `main`, although we recently pushed `master`. Which one is the correct one? Should we delete the other one?

**Comment by willdurand** [comment]
> Looks like the main branch is `main`, although we recently pushed `master`. Which one is the correct one? Should we delete the other one?

It should be `main`

**Comment by wagnerand** [comment]
Looks like [`85d91f5` (#173)](https://github.com/mozilla-extensions/xpi-manifest/pull/173/commits/85d91f5ff3da961f552250592f9f71e033a43ad9) is on `master` only.

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
> Looks like the main branch is `main`, although we recently pushed `master`. Which one is the correct one? Should we delete the other one?

Deleted `master`, ty.

**Pull request merged**
