### PR TITLE
Rename addons-search-experiment to addons-search-detection

### PR DESCRIPTION
**Pull request by willdurand**
See also: https://github.com/mozilla-extensions/addons-search-experiment/pull/8

### CODE REVIEW

**Review by wagnerand — APPROVED** [review]

**Comment by wagnerand** [comment]
@escapewindow I am not sure what the taskcluster comment above means. Can this PR be merged?

**Comment by willdurand** [comment]
> @escapewindow I am not sure what the taskcluster comment above means. Can this PR be merged?

This is because I created a PR with a fork given that I cannot push directly to this repo.

**Comment by wagnerand** [comment]
We also need to update https://github.com/mozilla-extensions/xpi-manifest/blob/c9922702c2edf2b0e76394629fe81a5ab6110521/taskcluster/ci/config.yml#L168-L171

**Review by wagnerand — APPROVED** [review]
This is fine, sorry for the confusion Will!

**Pull request merged**
